alias dus='du -sh'
alias l='ls -F'
alias ud='sudo aptitude update && sudo aptitude upgrade'
alias ack='ack-grep --color-lineno="bold dark red"'
alias d='df -h'
alias gdb='gdb -q'
alias v='vim'
alias gv='gvim'
