alias dus='du -sh'
alias l='ls -F'
alias ack='ack-grep --color-lineno="bold dark red"'
alias d='df -h'
alias gdb='gdb -q'
alias v='vim'
alias gv='gvim'
alias ag='apt-get'
alias ac='apt-cache'
alias ap='aptitude'
alias ud='sudo ap update && sudo ap upgrade'
alias aps='apt-cache search'
