#!/bin/bash

pushd $HOME
rm -f ~/.aliases ~/.bashrc ~/.inputrc ~/.zshrc ~/.pentadactylrc ~/.tmux.conf
rm -f ~/.gdbinit ~/.tigrc
rm -f ~/.i3/config ~/.xmodmaprc ~/.xinitrc ~/.i3status.conf ~/.i3/keys.sh
rm -f ~/.kde/share/config/gtkrc-2.0 ~/.gitconfig
rm -f ~/.screenrc ~/.kde/share/config/kglobalshortcutsrc 
rm -f ~/.kde/share/apps/konsole/konsoleui.rc

ln -s $HOME/.dotfiles/aliases ~/.aliases
ln -s $HOME/.dotfiles/bashrc ~/.bashrc
ln -s $HOME/.dotfiles/inputrc ~/.inputrc
ln -s $HOME/.dotfiles/zshrc ~/.zshrc
ln -s $HOME/.dotfiles/pentadactylrc ~/.pentadactylrc
ln -s $HOME/.dotfiles/tmux.conf ~/.tmux.conf
ln -s $HOME/.dotfiles/gdbinit ~/.gdbinit
ln -s $HOME/.dotfiles/tigrc ~/.tigrc
ln -s $HOME/.dotfiles/screenrc ~/.screenrc
ln -s $HOME/.dotfiles/gitconfig ~/.gitconfig
ln -s $HOME/.dotfiles/kglobalshortcutsrc ~/.kde/share/config/kglobalshortcutsrc 
ln -s $HOME/.dotfiles/konsoleui.rc ~/.kde/share/apps/konsole/konsoleui.rc
mkdir -p ~/.i3
ln -s $HOME/.dotfiles/i3-config ~/.i3/config
ln -s $HOME/.dotfiles/xmodmaprc ~/.xmodmaprc
ln -s $HOME/.dotfiles/xinitrc ~/.xinitrc
ln -s $HOME/.dotfiles/i3status.conf ~/.i3status.conf
ln -s $HOME/.dotfiles/i3-keys ~/.i3/keys.sh
ln -s $HOME/.dotfiles/gtkrc-2.0 ~/.kde/share/config/gtkrc-2.0
popd
