#!/bin/bash

pushd $HOME
rm -f ~/.aliases ~/.bashrc ~/.inputrc ~/.zshrc ~/.pentadactylrc ~/.tmux.conf
rm -f ~/.i3/config ~/.xmodmap ~/.xinitrc
ln -s $HOME/.dotfiles/aliases ~/.aliases
ln -s $HOME/.dotfiles/bashrc ~/.bashrc
ln -s $HOME/.dotfiles/inputrc ~/.inputrc
ln -s $HOME/.dotfiles/zshrc ~/.zshrc
ln -s $HOME/.dotfiles/pentadactylrc ~/.pentadactylrc
ln -s $HOME/.dotfiles/tmux.conf ~/.tmux.conf
mkdir -p ~/.i3
ln -s $HOME/.dotfiles/i3-config ~/.i3/config
ln -s $HOME/.dotfiles/xmodmap ~/.xmodmap
ln -s $HOME/.dotfiles/xinitrc ~/.xinitrc
popd
