#!/bin/bash

rm -f ~/.bash_aliases ~/.bashrc ~/.inputrc ~/.zshrc
ln -s .dotfiles/bash_aliases ~/.bash_aliases
ln -s .dotfiles/bashrc ~/.bashrc
ln -s .dotfiles/inputrc ~/.inputrc
ln -s .dotfiles/zshrc ~/.zshrc
